version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - PROXY_DOMAIN=awsmihome2612.tk
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /home/ubuntu/abc:/config
    ports:
      - 8443:8443
    restart: unless-stopped
